# create:
# conda env create --file environment.yml
# update:
# conda env update --file environment.yml --prune
name: nflows

channels:
  - conda-forge
  - pytorch

dependencies:
  - autoflake
  - black
  - cudatoolkit
  - flake8
  - isort
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pip:
    - torchtestcase
    - -e .  # install package in development mode
    - umnn
  - pytest
  - python
  - pytorch
  - pyyaml
  - tensorboard
  - tqdm
 
