# create:
# conda env create --file environment.yml
# update:
# conda env update --file environment.yml --prune
name: nflows

channels:
  - conda-forge
  - pytorch

dependencies:
  - autopep8
  - autoflake
  - black
  - cudatoolkit
  - flake8
  - isort
  - jupyter
  - matplotlib
  - numpy
  - pillow
  - pip
  - pip:
    - pyro-ppl
    - torchtestcase
    - -e .  # install package in development mode
  - pytest
  - pytest-pep8
  - python
  - pytorch
  - pyyaml
  - rope
  - scikit-learn
  - scipy
  - seaborn
  - tensorboard
  - tqdm
 
